# Generated by Django 5.0.6 on 2024-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
